apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: vulnova-prod
  labels:
    app.kubernetes.io/name: vulnova
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: vulnova
    app.kubernetes.io/component: postgres
