apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: vulnova-prod
  labels:
    app.kubernetes.io/name: vulnova
    app.kubernetes.io/component: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vulnova
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vulnova
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg16
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: vulnova-config
            - secretRef:
                name: vulnova-secrets
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 4096Mi
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - vulnova_admin
                - -d
                - vulnova_prod_db
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - vulnova_admin
                - -d
                - vulnova_prod_db
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
