"""Jira Finding & Status Mapper Module."""

from typing import Any, Dict, Optional

from app.infrastructure.database.models.assessment import SecurityFindingModel


class JiraFindingMapper:
    """Formats Vulnova security findings into Jira issue payloads."""

    @staticmethod
    def format_summary(finding: SecurityFindingModel) -> str:
        """Format Jira issue summary line."""
        sev = finding.severity.upper() if finding.severity else "HIGH"
        return f"[{sev}] Security Vulnerability: {finding.title}"

    @staticmethod
    def format_description_text(
        finding: SecurityFindingModel,
        asset_name: Optional[str] = None,
        ai_remediation_summary: Optional[str] = None,
    ) -> str:
        """Format Jira issue description text (Markdown-compatible text)."""
        target = asset_name or "Enterprise Target Asset"
        cve = finding.cve_id or "N/A"
        cwe = finding.cwe_id or "N/A"
        score = finding.risk_score or 7.5

        lines = [
            "h2. Vulnerability Details",
            f"* Title: {finding.title}",
            f"* Severity: {finding.severity}",
            f"* CVSS / Risk Score: {score}",
            f"* CVE Reference: {cve}",
            f"* CWE Reference: {cwe}",
            f"* Category: {finding.category}",
            f"* Target Asset: {target}",
            "",
            "h2. Finding Description",
            f"{finding.description}",
            "",
            "h2. Evidence Summary",
            f"Finding ID: {finding.id}",
        ]

        if finding.remediation:
            lines.extend(
                [
                    "",
                    "h2. Recommended Remediation",
                    f"{finding.remediation}",
                ]
            )

        if ai_remediation_summary:
            lines.extend(
                [
                    "",
                    "h2. AI Security Analyst Fix Guidance",
                    f"{ai_remediation_summary}",
                ]
            )

        lines.extend(
            [
                "",
                "----",
                "Auto-generated by Vulnova Enterprise Security Operations Platform.",
            ]
        )

        return "\n".join(lines)

    @staticmethod
    def format_adf_description(
        finding: SecurityFindingModel,
        asset_name: Optional[str] = None,
        ai_remediation_summary: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Format Jira Atlassian Document Format (ADF) JSON structure."""
        text = JiraFindingMapper.format_description_text(
            finding, asset_name, ai_remediation_summary
        )
        paragraphs = []
        for line in text.split("\n"):
            if not line.strip():
                continue
            paragraphs.append(
                {"type": "paragraph", "content": [{"type": "text", "text": line}]}
            )

        return {
            "version": 1,
            "type": "doc",
            "content": (
                paragraphs
                if paragraphs
                else [
                    {
                        "type": "paragraph",
                        "content": [{"type": "text", "text": finding.title}],
                    }
                ]
            ),
        }


class ControlledJiraStatusMapper:
    """Controlled state transition layer mapping Jira status changes to Vulnova finding state transitions."""

    # Map external Jira status strings to internal Vulnova lifecycle states
    STATUS_TRANSITION_MAP: Dict[str, str] = {
        "DONE": "RESOLVED",
        "CLOSED": "RESOLVED",
        "RESOLVED": "RESOLVED",
        "IN PROGRESS": "IN_REMEDIATION",
        "IN REVIEW": "IN_REMEDIATION",
        "IN DEVELOPMENT": "IN_REMEDIATION",
        "REOPENED": "CONFIRMED",
        "OPEN": "CONFIRMED",
        "TO DO": "CONFIRMED",
        "BACKLOG": "CONFIRMED",
    }

    @classmethod
    def map_jira_status_to_vulnova_state(
        cls, external_status: str, current_vulnova_status: str
    ) -> str:
        """Map external status safely through controlled transition rules."""
        normalized = external_status.upper().strip()
        mapped_state = cls.STATUS_TRANSITION_MAP.get(normalized)
        if not mapped_state:
            # Default: do not mutate internal status if transition is unmapped
            return current_vulnova_status
        return mapped_state
