"""GitHub Finding & Status Mapper Module."""

from typing import Dict, List, Optional

from app.infrastructure.database.models.assessment import SecurityFindingModel


class GitHubFindingMapper:
    """Formats Vulnova security findings into GitHub Issue Markdown payloads."""

    @staticmethod
    def format_title(finding: SecurityFindingModel) -> str:
        """Format GitHub issue title."""
        sev = finding.severity.upper() if finding.severity else "HIGH"
        return f"[{sev}] Security Vulnerability: {finding.title}"

    @staticmethod
    def format_body(
        finding: SecurityFindingModel,
        asset_name: Optional[str] = None,
        ai_remediation_summary: Optional[str] = None,
    ) -> str:
        """Format GitHub issue body in GitHub-Flavored Markdown."""
        target = asset_name or "Enterprise Target Asset"
        cve = finding.cve_id or "N/A"
        cwe = finding.cwe_id or "N/A"
        score = finding.risk_score or 7.5

        lines = [
            f"# 🛡️ Security Vulnerability Report: {finding.title}",
            "",
            "| Metric | Value |",
            "| --- | --- |",
            f"| **Severity** | `{finding.severity}` |",
            f"| **CVSS / Risk Score** | `{score}` |",
            f"| **CVE Reference** | `{cve}` |",
            f"| **CWE Reference** | `{cwe}` |",
            f"| **Category** | `{finding.category}` |",
            f"| **Target Asset** | `{target}` |",
            "",
            "## 📝 Vulnerability Description",
            f"{finding.description}",
            "",
            "## 🔬 Evidence & Finding Summary",
            f"- **Finding ID**: `{finding.id}`",
        ]

        if finding.remediation:
            lines.extend(
                [
                    "",
                    "## 🛠️ Recommended Remediation",
                    f"{finding.remediation}",
                ]
            )

        if ai_remediation_summary:
            lines.extend(
                [
                    "",
                    "## 🤖 AI Security Analyst Fix Recommendations",
                    "```markdown",
                    f"{ai_remediation_summary}",
                    "```",
                ]
            )

        lines.extend(
            [
                "",
                "---",
                "*Auto-generated by Vulnova Enterprise Security Operations Platform.*",
            ]
        )

        return "\n".join(lines)


class ControlledGitHubStatusMapper:
    """Controlled state transition layer mapping GitHub issue status changes to Vulnova finding state transitions."""

    # Map external GitHub issue states to internal Vulnova lifecycle states
    STATUS_TRANSITION_MAP: Dict[str, str] = {
        "CLOSED": "RESOLVED",
        "OPEN": "CONFIRMED",
        "IN_PROGRESS": "IN_REMEDIATION",
    }

    @classmethod
    def map_github_status_to_vulnova_state(
        cls,
        external_state: str,
        labels: Optional[List[str]] = None,
        current_vulnova_status: str = "CONFIRMED",
    ) -> str:
        """Map external GitHub state safely through controlled transition rules."""
        state_norm = external_state.upper().strip()
        if state_norm == "CLOSED":
            return "RESOLVED"

        if labels and any(
            "in-progress" in label.lower() or "wip" in label.lower() for label in labels
        ):
            return "IN_REMEDIATION"

        mapped_state = cls.STATUS_TRANSITION_MAP.get(state_norm)
        if not mapped_state:
            return current_vulnova_status
        return mapped_state
