apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vulnova-frontend-hpa
  namespace: vulnova-prod
  labels:
    app.kubernetes.io/name: vulnova
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vulnova-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
