"""Slack Webhook Provider utilizing Slack Block Kit JSON format."""

from datetime import datetime, timezone
from typing import Any, Dict

import httpx
import structlog

from app.application.notifications.dto import (
    NotificationDeliveryResponse,
    SecurityNotificationEventDTO,
)

logger = structlog.get_logger(__name__)


class SlackWebhookProvider:
    """Dispatches real-time security alert webhooks to Slack Workspaces using Block Kit formatting."""

    SEVERITY_COLORS = {
        "CRITICAL": "#DC2626",
        "HIGH": "#F97316",
        "MEDIUM": "#EAB308",
        "LOW": "#3B82F6",
        "INFO": "#10B981",
    }

    @staticmethod
    def format_block_kit_payload(event: SecurityNotificationEventDTO) -> Dict[str, Any]:
        """Build Slack Block Kit JSON payload."""
        sev = event.severity.upper() if event.severity else "HIGH"
        color = SlackWebhookProvider.SEVERITY_COLORS.get(sev, "#6B7280")
        target = event.target_asset or "Enterprise Target Asset"
        score_str = str(event.risk_score) if event.risk_score is not None else "N/A"

        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"🛡️ Vulnova Alert: {event.title[:140]}",
                    "emoji": True,
                },
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Severity:* `{sev}`"},
                    {"type": "mrkdwn", "text": f"*Risk Score:* `{score_str}`"},
                    {"type": "mrkdwn", "text": f"*Event Type:* `{event.event_type}`"},
                    {"type": "mrkdwn", "text": f"*Target:* `{target}`"},
                ],
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"{event.description[:2000]}",
                },
            },
            {"type": "divider"},
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"Auto-generated by *Vulnova Enterprise Security Platform* | {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
                    }
                ],
            },
        ]

        return {
            "attachments": [
                {
                    "color": color,
                    "blocks": blocks,
                }
            ]
        }

    async def send_alert(
        self,
        channel_id: str,
        webhook_url: str,
        event: SecurityNotificationEventDTO,
    ) -> NotificationDeliveryResponse:
        """Send Slack incoming webhook alert."""
        payload = self.format_block_kit_payload(event)
        now_iso = datetime.now(timezone.utc).isoformat()

        async with httpx.AsyncClient(timeout=10.0) as client:
            try:
                res = await client.post(webhook_url, json=payload)
                if res.status_code not in (200, 201, 204):
                    logger.error(
                        "slack.delivery_failed",
                        channel_id=channel_id,
                        status_code=res.status_code,
                        body=res.text,
                    )
                    return NotificationDeliveryResponse(
                        channel_id=channel_id,
                        provider="slack",
                        event_type=event.event_type,
                        status="FAILED",
                        status_code=res.status_code,
                        delivered_at=now_iso,
                        error_message=f"Slack returned HTTP {res.status_code}: {res.text[:150]}",
                    )

                logger.info("slack.delivered_successfully", channel_id=channel_id)
                return NotificationDeliveryResponse(
                    channel_id=channel_id,
                    provider="slack",
                    event_type=event.event_type,
                    status="DELIVERED",
                    status_code=res.status_code,
                    delivered_at=now_iso,
                )
            except Exception as e:
                logger.error(
                    "slack.http_exception", channel_id=channel_id, error=str(e)
                )
                return NotificationDeliveryResponse(
                    channel_id=channel_id,
                    provider="slack",
                    event_type=event.event_type,
                    status="FAILED",
                    status_code=500,
                    delivered_at=now_iso,
                    error_message=f"HTTP connection failed: {str(e)}",
                )
